/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author hugo
 */
public class LeJeuLoto extends javax.swing.JFrame {

    /**
     * Creates new form LeJeuLoto
     */
    public LeJeuLoto() {
        //initiaisation des différents composants de la fenêtre
        initComponents();
        
        //initialisation des différentes variables
        choixOpt = 1;
        nbCol = 5;
        nbNum = 15;
        //création de la liste qui sert à gérer les différents joueurs
        lstJ = new LesJoueurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonJ1 = new javax.swing.JButton();
        jButtonJ2 = new javax.swing.JButton();
        jButtonJ3 = new javax.swing.JButton();
        jButtonJ4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAjoutJoueur = new javax.swing.JMenuItem();
        jMenuItemAjoutLot = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOptJeu = new javax.swing.JMenuItem();
        jMenuItemDemJeu = new javax.swing.JMenuItem();
        jMenuItemAchCar = new javax.swing.JMenuItem();
        jMenuItemCont = new javax.swing.JMenuItem();
        jMenuItemRecom = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        jButtonJ1.setText("Joueur 1");
        jButtonJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonJ1);

        jButtonJ2.setText("Joueur 2");
        jButtonJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonJ2);

        jButtonJ3.setText("Joueur 3");
        jButtonJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonJ3);

        jButtonJ4.setText("Joueur 4");
        jButtonJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonJ4);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Cadeau: ");
        jPanel5.add(jLabel1);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.add(jScrollPane1);

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jButton1.setText("Tirage");
        jPanel8.add(jButton1);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel5);

        jPanel8.add(jPanel9);

        jButton2.setText("Arreter");
        jPanel8.add(jButton2);

        jPanel6.add(jPanel8);

        jPanel4.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        jLabel3.setText("Historique du tirage des boules");
        jPanel10.add(jLabel3);

        jLabel4.setText("Option Choisie:");
        jPanel10.add(jLabel4);

        jPanel4.add(jPanel10, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        jMenu2.setText("Ajout");

        jMenuItemAjoutJoueur.setText("Joueur");
        jMenuItemAjoutJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjoutJoueurActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAjoutJoueur);

        jMenuItemAjoutLot.setText("Lot");
        jMenu2.add(jMenuItemAjoutLot);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Action");

        jMenuItemOptJeu.setText("Option Jeu");
        jMenu1.add(jMenuItemOptJeu);

        jMenuItemDemJeu.setText("Demarrer Jeu");
        jMenu1.add(jMenuItemDemJeu);

        jMenuItemAchCar.setText("Acheter Cartes");
        jMenuItemAchCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAchCarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAchCar);

        jMenuItemCont.setText("Continuer");
        jMenu1.add(jMenuItemCont);

        jMenuItemRecom.setText("Recommencer");
        jMenu1.add(jMenuItemRecom);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAchCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAchCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAchCarActionPerformed

    private void jMenuItemAjoutJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjoutJoueurActionPerformed
        // TODO add your handling code here:
        if(lstJ.getNbJoueur()<4){ //S'il y a moins de 4 joueurs déjà créé:
            SaisieJoueurDlg diag = new SaisieJoueurDlg(this, true);
            diag.setVisible(true);
            if(diag.getOk()){
                lstJ.ajoutJoueur(diag.getJoueur()); //Ajout du joueur créé dans la fenêtre SaisieJoueurDlg dans la liste servant à les gérér
            }
            PlaceJ(); //Affichage des Joueurs sur les boutons
        }else{ //S'il y'a 4 joueurs ou plus, ne rien faire
            jLabel2.setText("Il y a trop de joueurs");
        }
    }//GEN-LAST:event_jMenuItemAjoutJoueurActionPerformed

    private void jButtonJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ1ActionPerformed
        // TODO add your handling code here:
        //Bouton servant à afficher les infos du Joueur 1
        VisuJoueurDlg diag = new VisuJoueurDlg(this, true, lstJ.getJoueur(0));
        diag.setVisible(true);
    }//GEN-LAST:event_jButtonJ1ActionPerformed

    private void jButtonJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ2ActionPerformed
        // TODO add your handling code here:
        //Bouton servant à afficher les infos du Joueur 2
        VisuJoueurDlg diag = new VisuJoueurDlg(this, true, lstJ.getJoueur(1));
        diag.setVisible(true);
    }//GEN-LAST:event_jButtonJ2ActionPerformed

    private void jButtonJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ3ActionPerformed
        // TODO add your handling code here:
        //Bouton servant à afficher les infos du Joueur 3
        VisuJoueurDlg diag = new VisuJoueurDlg(this, true, lstJ.getJoueur(2));
        diag.setVisible(true);
    }//GEN-LAST:event_jButtonJ3ActionPerformed

    private void jButtonJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ4ActionPerformed
        // TODO add your handling code here:
        //Bouton servant à afficher les infos du Joueur 3
        VisuJoueurDlg diag = new VisuJoueurDlg(this, true, lstJ.getJoueur(3));
        diag.setVisible(true);
    }//GEN-LAST:event_jButtonJ4ActionPerformed
    
    private void PlaceJ(){
        //Fonction servant à afficher les noms des Joueurs et leur couleur sur les boutons
        for(int i=0; i<lstJ.getNbJoueur(); i++){
            javax.swing.JButton comp = (javax.swing.JButton) jPanel3.getComponent(i);
            comp.setText(lstJ.getJoueur(i).getPseudo());
            comp.setBackground(lstJ.getJoueur(i).getCouleur());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeJeuLoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeJeuLoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeJeuLoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeJeuLoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeJeuLoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonJ1;
    private javax.swing.JButton jButtonJ2;
    private javax.swing.JButton jButtonJ3;
    private javax.swing.JButton jButtonJ4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAchCar;
    private javax.swing.JMenuItem jMenuItemAjoutJoueur;
    private javax.swing.JMenuItem jMenuItemAjoutLot;
    private javax.swing.JMenuItem jMenuItemCont;
    private javax.swing.JMenuItem jMenuItemDemJeu;
    private javax.swing.JMenuItem jMenuItemOptJeu;
    private javax.swing.JMenuItem jMenuItemRecom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private int choixOpt;
    private int nbNum;
    private int nbCol;
    private LesJoueurs lstJ;
}
