import java.awt.*; 
import javax.swing.*;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author hugo
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {

    private Joueur nj;
    private boolean ok;
    
    
    /**
     * Creates new form SaisieJoueurDlg
     */
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal); //
        initComponents();
        
        //initialisation des attributs
        this.nj = new Joueur();
        this.ok = false;        
    }
    
    //accesseurs
    public Joueur getJoueur(){ //pour récupérer le joueur saisi
        return this.nj;
    }
    public boolean getOk(){ //pour connaitre le mode de fermeture de la boite de dialogue
        return this.ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitre = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jPanelSaisie = new javax.swing.JPanel();
        jPanelSaisiePseudo = new javax.swing.JPanel();
        jLabelPseudo = new javax.swing.JLabel();
        jPanelResultPseudo = new javax.swing.JPanel();
        Pseudo = new javax.swing.JTextField();
        jPanelSaisieSolde = new javax.swing.JPanel();
        jLabelSolde = new javax.swing.JLabel();
        jPanelResultSolde = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelSaisieCouleur = new javax.swing.JPanel();
        jLabelCouleur = new javax.swing.JLabel();
        jPanelResultCouleur = new javax.swing.JPanel();
        BChoisir = new javax.swing.JButton();
        PanCouleur = new javax.swing.JPanel();
        jPanelBoutons = new javax.swing.JPanel();
        BAnnuler = new javax.swing.JButton();
        BValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitre.setText("Ajoiut d'un nouveau Joueur");
        jPanelTitre.add(jLabelTitre);

        getContentPane().add(jPanelTitre, java.awt.BorderLayout.NORTH);

        jPanelSaisie.setLayout(new java.awt.GridLayout(3, 2));

        jPanelSaisiePseudo.setLayout(new java.awt.GridLayout());

        jLabelPseudo.setText("Pseudo ?");
        jPanelSaisiePseudo.add(jLabelPseudo);

        jPanelSaisie.add(jPanelSaisiePseudo);

        jPanelResultPseudo.setLayout(new javax.swing.BoxLayout(jPanelResultPseudo, javax.swing.BoxLayout.LINE_AXIS));
        jPanelResultPseudo.add(Pseudo);

        jPanelSaisie.add(jPanelResultPseudo);

        jPanelSaisieSolde.setLayout(new java.awt.GridLayout());

        jLabelSolde.setText("Solde ? ");
        jPanelSaisieSolde.add(jLabelSolde);

        jPanelSaisie.add(jPanelSaisieSolde);

        jPanelResultSolde.setLayout(new javax.swing.BoxLayout(jPanelResultSolde, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("20.0€");
        jPanelResultSolde.add(jLabel1);

        jPanelSaisie.add(jPanelResultSolde);

        jPanelSaisieCouleur.setLayout(new java.awt.GridLayout());

        jLabelCouleur.setText("Couleur ?");
        jPanelSaisieCouleur.add(jLabelCouleur);

        jPanelSaisie.add(jPanelSaisieCouleur);

        jPanelResultCouleur.setLayout(new java.awt.GridLayout(1, 2));

        BChoisir.setText("Choisir");
        BChoisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BChoisirActionPerformed(evt);
            }
        });
        jPanelResultCouleur.add(BChoisir);
        jPanelResultCouleur.add(PanCouleur);

        jPanelSaisie.add(jPanelResultCouleur);

        getContentPane().add(jPanelSaisie, java.awt.BorderLayout.CENTER);

        jPanelBoutons.setLayout(new java.awt.GridLayout(1, 2));

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        jPanelBoutons.add(BAnnuler);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        jPanelBoutons.add(BValider);

        getContentPane().add(jPanelBoutons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BChoisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BChoisirActionPerformed
        // TODO add your handling code here:
        //on utilise directement la boite de dialogue JColorChooser pour ouvrir une boite de dialogue avec un sélecteur de couleur
        JColorChooser diag = new JColorChooser();
        Color coul = diag.showDialog(this, "Couleur", Color.red);
        //retourne la couleur sélectionnée ou null
        //si non null, on retourne la couleur du joueur
        if(coul != null){
            this.nj.setCouleur(coul);
            PanCouleur.setBackground(coul); //panneau qui affiche la couleur préféré
        }else{ //Sinon, j'ai choisi la couleur roige par défaut
            this.nj.setCouleur(Color.red);
            PanCouleur.setBackground(this.nj.getCouleur()); //panneau qui affiche la couleur préféré            
        }
    }//GEN-LAST:event_BChoisirActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        //Fermer la fenêtre et prendre en compte la création du joueur
        if(!Pseudo.getText().isEmpty()){ //Si on a bien rentré un pseudo pour notre joueur
            String ps = Pseudo.getText();
            this.nj.setPseudo(ps);
            //on a cliqué sur Valider donc le booléen ok est mis à true
            this.ok = true;
            //on ferme maintenant la boite de dialogue
            this.setVisible(false);
            //on peut libérer plus vite de l'espace
            this.dispose();
        }
    }//GEN-LAST:event_BValiderActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        //Fermer la fenêtre sans faire de changement
        this.ok = false;
        this.setVisible(false);
        this.dispose(); 
    }//GEN-LAST:event_BAnnulerActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BChoisir;
    private javax.swing.JButton BValider;
    private javax.swing.JPanel PanCouleur;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCouleur;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JLabel jLabelSolde;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelBoutons;
    private javax.swing.JPanel jPanelResultCouleur;
    private javax.swing.JPanel jPanelResultPseudo;
    private javax.swing.JPanel jPanelResultSolde;
    private javax.swing.JPanel jPanelSaisie;
    private javax.swing.JPanel jPanelSaisieCouleur;
    private javax.swing.JPanel jPanelSaisiePseudo;
    private javax.swing.JPanel jPanelSaisieSolde;
    private javax.swing.JPanel jPanelTitre;
    // End of variables declaration//GEN-END:variables
}
