
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author hugo
 */
public class VisuJoueurDlg extends javax.swing.JDialog {

    /**
     * Creates new form VisuJoueurDlg
     */
    //Constructeur par défaut
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); //initialisation des composants
    }
    
    //constructeur standard
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal, Joueur j) {
        super(parent, modal);
        initComponents(); //initialisation des composants

        this.lejoueur=j; //référencement de l'attribut
        initInfos(); //Affichage des infos du joueur
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfo = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jPanelInformation = new javax.swing.JPanel();
        jPanelTemplate = new javax.swing.JPanel();
        jPanelTemplatePseudo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTemplateCouleur = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelTemplateSolde = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPaneResult = new javax.swing.JPanel();
        jPaneResultPseudo = new javax.swing.JPanel();
        jLabelPseudo = new javax.swing.JLabel();
        jPaneResultCouleur = new javax.swing.JPanel();
        jPaneResultSolde = new javax.swing.JPanel();
        jLabelSolde = new javax.swing.JLabel();
        jPanelEdit = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jPanelImage = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();
        jPanelBoutons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitre.setText("Informations relatives à un joueur");
        jPanelInfo.add(jLabelTitre);

        getContentPane().add(jPanelInfo, java.awt.BorderLayout.NORTH);

        jPanelInformation.setLayout(new java.awt.GridLayout(1, 4));

        jPanelTemplate.setLayout(new java.awt.GridLayout(3, 1));

        jPanelTemplatePseudo.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("Pseudo");
        jPanelTemplatePseudo.add(jLabel2);

        jPanelTemplate.add(jPanelTemplatePseudo);

        jPanelTemplateCouleur.setLayout(new javax.swing.BoxLayout(jPanelTemplateCouleur, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Couleur");
        jPanelTemplateCouleur.add(jLabel3);

        jPanelTemplate.add(jPanelTemplateCouleur);

        jPanelTemplateSolde.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setText("Solde");
        jPanelTemplateSolde.add(jLabel4);

        jPanelTemplate.add(jPanelTemplateSolde);

        jPanelInformation.add(jPanelTemplate);

        jPaneResult.setLayout(new java.awt.GridLayout(3, 1));

        jPaneResultPseudo.setLayout(new javax.swing.BoxLayout(jPaneResultPseudo, javax.swing.BoxLayout.LINE_AXIS));
        jPaneResultPseudo.add(jLabelPseudo);

        jPaneResult.add(jPaneResultPseudo);

        javax.swing.GroupLayout jPaneResultCouleurLayout = new javax.swing.GroupLayout(jPaneResultCouleur);
        jPaneResultCouleur.setLayout(jPaneResultCouleurLayout);
        jPaneResultCouleurLayout.setHorizontalGroup(
            jPaneResultCouleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        jPaneResultCouleurLayout.setVerticalGroup(
            jPaneResultCouleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPaneResult.add(jPaneResultCouleur);

        jPaneResultSolde.setLayout(new javax.swing.BoxLayout(jPaneResultSolde, javax.swing.BoxLayout.LINE_AXIS));
        jPaneResultSolde.add(jLabelSolde);

        jPaneResult.add(jPaneResultSolde);

        jPanelInformation.add(jPaneResult);

        jPanelEdit.setLayout(new javax.swing.BoxLayout(jPanelEdit, javax.swing.BoxLayout.LINE_AXIS));

        Edition.setEditable(false);
        Edition.setColumns(20);
        Edition.setRows(5);
        Edition.setAutoscrolls(false);
        jScrollPane1.setViewportView(Edition);

        jPanelEdit.add(jScrollPane1);

        jPanelInformation.add(jPanelEdit);

        jPanelImage.setLayout(new java.awt.GridLayout(1, 0));
        jPanelImage.add(Photo);

        jPanelInformation.add(jPanelImage);

        getContentPane().add(jPanelInformation, java.awt.BorderLayout.CENTER);

        jPanelBoutons.setLayout(new java.awt.GridLayout(1, 2));
        jPanelBoutons.add(jButton1);

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });
        jPanelBoutons.add(jButtonFermer);

        getContentPane().add(jPanelBoutons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        // TODO add your handling code here:
        //Fermer la fenêtre de dialogue sans faire de changement
        this.setVisible(false); 
        this.dispose();
    }//GEN-LAST:event_jButtonFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueurDlg dialog = new VisuJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void initInfos(){ //Fonction affichant les informations du Joueur à l'endroit désigné
        jLabelPseudo.setText(lejoueur.getPseudo());
        jPaneResultCouleur.setBackground(lejoueur.getCouleur());
        Photo.setIcon(lejoueur.getPhoto());
        jLabelSolde.setText(lejoueur.getSolde() + "");
        Edition.setText("Aucun lot gagné"); //texte mis par défaut en attendant de continuer sur le projet et d'ajouter les lots gagnés
    }
    
    
    private Joueur lejoueur;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Edition;
    private javax.swing.JButton Photo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JLabel jLabelSolde;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPaneResult;
    private javax.swing.JPanel jPaneResultCouleur;
    private javax.swing.JPanel jPaneResultPseudo;
    private javax.swing.JPanel jPaneResultSolde;
    private javax.swing.JPanel jPanelBoutons;
    private javax.swing.JPanel jPanelEdit;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JPanel jPanelTemplate;
    private javax.swing.JPanel jPanelTemplateCouleur;
    private javax.swing.JPanel jPanelTemplatePseudo;
    private javax.swing.JPanel jPanelTemplateSolde;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
